server:
  port: 8080

spring:
  application:
    name: EventScheduleMS
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ms_event_schedule}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

scheduler:
#  cron: "*/10 * * * * ?" # Toda meia noide -> "0 0 0 * * ?"
  cron: "0 0 0 * * ?"
