version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: mspostgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ms_event_schedule
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - eventschedule-network

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ms_event_schedule
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./src/main:/app/src/main
    networks:
      - eventschedule-network

volumes:
  postgres-data:

networks:
  eventschedule-network:
    driver: bridge
